<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Young+Serif:wght@400&display=swap" />
    <link rel="stylesheet" href="{{ asset('css/aboutnon.css') }}">
  </head>
  <body>
    <div class="main-container">
      <div class="frame">
        <div class="frame-1">
          <div class="logo"><span class="spt">SPT</span></div>
        </div>

        <div class="frame-2">
          <div class="group">
            <a href="homenon"><span class="home-5">HOME</span></a>
          </div>

          <div class="group-4">
            <div class="line"></div>
            <div class="about-spark">
              <span class="about-spt-5">ABOUT SPT</span>
            </div>
          </div>
          <div class="group-6">
            <div class="our-product">
              <span class="our-product-7">OUR PRODUCT</span>
            </div>
          </div>
          <div class="group-8">
            <div class="contact-us">
              <span class="contact-us-9">CONTACT US</span>
            </div>
          </div>
        </div>
        
        <div class="frame-a">
          <div class="log">
            <div class="frame-b"><span class="login">Login</span></div>
          </div>
          <div class="log-c">
            <div class="frame-d"><span class="register">Register</span></div>
          </div>
        </div>
      </div>
      <span class="about-spt-e">ABOUT SPT</span
      ><span class="customer-satisfaction"
        >We always try to make our customer Happy. We provide all kind of
        facilities. <br />Your Satisfaction is our main priority</span
      >
      <div class="rectangle">
        <div class="home-product">
          <span class="home-f">Home</span><span class="space"> </span
          ><span class="slash">/</span
          ><span class="our-product-10"> Our Product</span>
        </div>
      </div>
      <div class="frame-11">
        <div class="frame-12">
          <div class="dbf-ceaaace"></div>
          <div class="line-13"></div>
        </div>
        <div class="frame-14">
          <div class="dbf-ceaaace-15"></div>
          <div class="line-16"></div>
        </div>
        <div class="frame-17">
          <div class="dbf-ceaaace-18"></div>
          <div class="line-19"></div>
        </div>
      </div>
      <span class="spt-1a">SPT</span>
      <div class="line-1b"></div>
      <span class="sahabat-pakan-ternak"
        >Sahabat Pakan Ternak adalah usaha yang bergerak di bidang penyediaan
        bahan baku pakan ternak, khususnya polar, biskuit, dan susu, yang
        diformulasikan untuk memenuhi kebutuhan nutrisi ternak secara optimal.
        Kami memahami bahwa kualitas pakan sangat menentukan kesehatan,
        pertumbuhan, dan produktivitas ternak, oleh karena itu kami menghadirkan
        bahan-bahan pilihan dengan standar mutu tinggi dan harga yang
        kompetitif. Dengan layanan yang ramah dan responsif, Sahabat Pakan
        Ternak berkomitmen menjadi mitra terbaik bagi para peternak, baik skala
        kecil maupun besar, yang ingin meningkatkan efisiensi usaha peternakan
        mereka. Melalui produk yang aman, bernutrisi, dan mudah diakses, kami
        siap mendukung kemajuan peternakan Indonesia secara berkelanjutan.</span
      ><span class="website-sahabat-pakan-ternak"
        >Website Sahabat Pakan Ternak dikembangkan untuk memudahkan peternak
        dalam mendapatkan informasi seputar pakan ternak secara cepat dan
        praktis. Melalui ini, peternak bisa membeli pakan, mengetahui kandungan
        yang terdapat dalam pakan, dan cara penggunaan yang tepat. Selain itu,
        website ini juga menjadi sarana untuk memperluas jangkauan peternak -
        peternak lainnya di seluruh wilayah sekitar ataupun luar sekitar.</span
      >
      <div class="gudang-pakan"></div>
      <div class="frame-1c">
        <div class="frame-1d">
          <div class="frame-1e">
            <div class="frame-1f"><span class="visi">Visi</span></div>
            <span class="beyond-no-everyday"
              >Beyond No. 1, <br />Everyday with Farmsco.</span
            >
          </div>
        </div>
        <div class="frame-20">
          <div class="frame-21">
            <div class="frame-22"><span class="misi">Misi</span></div>
            <span class="memimpin-industri-peternakan"
              >Memimpin Industri Peternakan babi dan Berkontribusi pada
              Kebahagiaan Pelanggan</span
            >
          </div>
        </div>
      </div>
      <div class="rectangle-23">
        <div class="flex-row-fc">
          <span class="spt-24">SPT</span
          ><span class="tentang-spt">Tentang SPT</span
          ><span class="perusahaan-peternakan-terintegrasi"
            >Perusahaan Peternakan terintegrasi<br />yang memberikan produk
            terbaik<br />kepada konsumen. Kami berpengalaman<br />di bidang
            peternakan dengan system<br />teknologi terbaru, serta spesialis
            dalam<br />bidang produksi hasil pertanian dan peternakan.</span
          >
          <div class="footer">
            <div class="logo-25"><span class="spt-26">SPT</span></div>
            <div class="group-27">
              <span class="tentang-spt-28">Tentang SPT</span
              ><span class="perusahaan-peternakan-terintegrasi-29"
                >Perusahaan Peternakan terintegrasi<br />yang memberikan produk
                terbaik<br />kepada konsumen. Kami berpengalaman<br />di bidang
                peternakan dengan systemt<br />eknologi terbaru, serta spesialis
                dalam<br />bidang produksi hasil pertanian dan peternakan.</span
              >
            </div>
          </div>
        </div>
        <div class="frame-2a">
          <div class="group-2b">
            <div class="home-2c"><span class="home-2d">HOME</span></div>
          </div>
          <div class="group-2e">
            <div class="about-spark-2f">
              <span class="about-spark-30">ABOUT SPT</span>
            </div>
          </div>
          <div class="group-31">
            <div class="our-product-32">
              <span class="our-product-33">OUR PRODUCT</span>
            </div>
          </div>
          <div class="group-34">
            <div class="contact-us-35">
              <span class="contact-us-36">CONTACT US</span>
            </div>
          </div>
        </div>
      </div>
      <div class="aerial-view-factory"></div>
      <div class="rectangle-37"></div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
