<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Young+Serif:wght@400&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lust:wght@400&display=swap" />
    <link rel="stylesheet" href="{{ asset('css/contactnon.css') }}">
  </head>
  <body>
    <div class="main-container">
      <div class="frame">
        <div class="frame-1">
          <div class="logo"><span class="spt">SPT</span></div>
        </div>

        <div class="frame-2">
  <div class="group">
    <div class="home">
      <a href="index.html" class="home-3">HOME</a>
    </div>
  </div>
  <div class="group-4">
    <div class="about-spark">
      <a href="about.html" class="about-spark-5">ABOUT SPT</a>
    </div>
  </div>
  <div class="group-6">
    <div class="our-product">
      <a href="product.html" class="our-product-7">OUR PRODUCT</a>
    </div>
  </div>
  <div class="group-8">
    <div class="line"></div>
    <div class="contact-us-9">
      <a href="contact.html" class="contact-us-a">CONTACT US</a>
    </div>
  </div>
</div>


        <div class="frame-b">
          <div class="log">
            <div class="frame-c"><span class="login">Login</span></div>
          </div>
          <div class="log-d">
            <div class="frame-e"><span class="login-f">Register</span></div>
          </div>
        </div>
      </div>
      <span class="contact-us-10">CONTACT US</span
      ><span class="customer-satisfaction"
        >We always try to make our customer Happy. We provide all kind of
        facilities. <br />Your Satisfaction is our main priority</span
      >
      <div class="rectangle">
        <div class="home-contact-us">
          <span class="home-11">Home</span><span class="nbsp"> </span
          ><span class="slash">/</span
          ><span class="contact-us-12"> Contact Us</span>
        </div>
      </div>
      <div class="flex-row-d">
        <div class="gudang-pakan"></div>
        <div class="regroup">
          <div class="frame-13">
            <div class="frame-14"></div>
            <div class="phone">
              <span class="phone-text">PHONE<br /></span
              ><span class="phone-number">03 5432 1234</span>
            </div>
          </div>
          <div class="frame-15">
            <div class="frame-16"></div>
            <div class="fax">
              <span class="fax-text">FAX<br /></span
              ><span class="fax-number">03 5432 1234</span>
            </div>
          </div>
          <div class="frame-17">
            <div class="frame-18"></div>
            <div class="email">
              <span class="email-text">EMAIL<br /></span
              ><span class="email-address">info@marcc.com.au</span>
            </div>
          </div>
        </div>
        <div class="spt-19">
          <div class="group-1a">
            <div class="sahabat-pakan-ternak">
              <span class="sahabat-pakan-ternak-text"
                >sahabat pakan ternak<br /></span
              ><span class="indonesia">Indonesia</span>
            </div>
            <span class="contact-us-1b"
              >Contact Us Have a question or need help? Send us a message —
              we're here for you!</span
            >
          </div>
          <div class="group-1c">
            <div class="text-field"><span class="name">Name</span></div>
            <div class="email-1d"><span class="email-1e">Email</span></div>
            <div class="tlp">
              <span class="phone-number-1f">Phone number</span>
            </div>
            <div class="button"><span class="kirim">KIRIM</span></div>
          </div>
        </div>
      </div>
      <div class="rectangle-20">
        <div class="flex-column-c">
          <span class="spt-21">SPT</span
          ><span class="tentang-spt">Tentang SPT</span
          ><span class="perusahaan-peternakan-terintegrasi"
            >Perusahaan Peternakan terintegrasi<br />yang memberikan produk
            terbaik<br />kepada konsumen. Kami berpengalaman<br />di bidang
            peternakan dengan system<br />teknologi terbaru, serta spesialis
            dalam<br />bidang produksi hasil pertanian dan peternakan.</span
          >
        </div>
        <div class="flex-column-fe">
          <div class="rectangle-22"><div class="d-f-e-dbd-bcdef"></div></div>
          <span class="scan-me">Scan Me</span>
          <div class="frame-23">
            <div class="group-24">
              <div class="home-25"><span class="home-26">HOME</span></div>
            </div>
            <div class="group-27">
              <div class="about-spark-28">
                <span class="about-spark-29">ABOUT SPT</span>
              </div>
            </div>
            <div class="group-2a">
              <div class="our-product-2b">
                <span class="our-product-2c">OUR PRODUCT</span>
              </div>
            </div>
            <div class="group-2d">
              <div class="contact-us-2e">
                <span class="contact-us-2f">CONTACT US</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="aerial-view-factory"></div>
      <div class="rectangle-30"></div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
