<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Young+Serif:wght@400&display=swap" />
    <link rel="stylesheet" href="{{ asset('css/homenon.css') }}">
  </head>
  <body>
    <div class="main-container">
      <div class="home-1">
        <div class="flex-column">
          <div class="frame">
            <div class="frame-2">
              <div class="logo"><span class="spt">SPT</span></div>
            </div>


            <div class="frame-3">
  <div class="group">
    <div class="line"></div>
    <div class="home-4">
      <a href="homenon"><span class="home-5">HOME</span></a>
    </div>
  </div>
  <div class="group-6">
    <div class="about-spark">
      <a href="about"><span class="about-spark-7">ABOUT SPT</span></a>
    </div>
  </div>
  <div class="group-8">
    <div class="our-product">
      <a href="#products"><span class="our-product-9">OUR PRODUCT</span></a>
    </div>
  </div>
  <div class="group-a">
    <div class="contact-us">
      <a href="contact"><span class="contact-us-b">CONTACT US</span></a>
    </div>
  </div>
</div>


            <div class="frame-c">
              <div class="log">
                <div class="frame-d"><span class="login">Login</span></div>
              </div>
              <div class="log-e">
                <div class="frame-f">
                  <span class="register">Register</span>
                </div>
              </div>
            </div>
          </div>
          <span class="sahabat-pakan-ternak">SAHABAT <br />PAKAN TERNAK</span
          ><span class="kami-hadir"
            >Kami hadir untuk memenuhi kebutuhan para peternak Indonesia
            dengan<br />menyediakan produk ternak yang diproduksi dengan
            sistem<br />teknologi termutakhir.</span
          >
          <div class="group-10">
            <div class="frame-11">
              <div class="group-12">
                <div class="home-13"><span class="home-14">HOME</span></div>
              </div>
              <div class="group-15">
                <div class="about-spark-16">
                  <span class="about-spark-17">ABOUT SPT</span>
                </div>
              </div>
              <div class="group-18">
                <div class="our-product-19">
                  <span class="our-product-1a">OUR PRODUCT</span>
                </div>
              </div>
              <div class="group-1b">
                <div class="contact-us-1c">
                  <span class="contact-us-1d">CONTACT US</span>
                </div>
              </div>
            </div>
            <div class="footer">
              <div class="logo-1e"><span class="spt-1f">SPT</span></div>
              <div class="group-20">
                <span class="tentang-spt">Tentang SPT</span
                ><span class="perusahaan-peternakan"
                  >Perusahaan Peternakan terintegrasi<br />yang memberikan
                  produk terbaik<br />kepada konsumen. Kami berpengalaman<br />di
                  bidang peternakan dengan system<br />teknologi terbaru, serta
                  spesialis dalam<br />bidang produksi hasil pertanian dan
                  peternakan.</span
                >
              </div>
              <div class="rectangle"></div>
            </div>
          </div>
          <div class="gudang-pakan"></div>
          <span class="sahabat-pakan-ternak-21">Sahabat Pakan Ternak</span
          ><span class="sahabat-pakan-ternak-22"
            >Sahabat Pakan Ternak adalah usaha yang bergerak di bidang
            penyediaan bahan baku pakan ternak, khususnya polar, biskuit, dan
            susu, yang diformulasikan untuk memenuhi kebutuhan nutrisi ternak
            secara optimal. <br /><br />Kami memahami bahwa kualitas pakan
            sangat menentukan kesehatan, pertumbuhan, dan produktivitas ternak,
            oleh karena itu kami menghadirkan bahan-bahan pilihan dengan standar
            mutu tinggi dan harga yang kompetitif</span
          >
          <div class="be-b-e"></div>
          <div class="dbf-ceaaace"></div>
          <div class="pppppppppp"><div class="rectangle-23"></div></div>
          <div class="rectangle-24"></div>
          <div class="pakan">
            <div class="frame-25">
              <div class="frame-26">
                
                <div class="frame-27"><span class="all">All</span></div>
              </div>
              <div class="frame-28">
                <div class="frame-29">
                  <span class="pakan-jadi">Pakan Jadi</span>
                </div>
              </div>
              <div class="frame-2a">
                <div class="frame-2b">
                  <span class="bahan-baku-pakan">Bahan Baku Pakan</span>
                </div>
              </div>
            </div>
            <div class="frame-2c">
              <div class="jadi">
                <div class="chatgpt-image"></div>
                <span class="bahan-pakan-babi">Bahan Pakan Babi</span>
              </div>
              <div class="biskuit">
                <div class="whatsapp-image"></div>
                <span class="bahan-pakan-biskuit">Biskuit</span>
              </div>
              <div class="susu">
                <div class="rounded-rectangle"></div>
                <span class="bahan-pakan-susu">Susu</span>
              </div>
              <div class="polar">
                <div class="whatsapp-image-2d"></div>
                <span class="bahan-polar">Polar</span>
              </div>
            </div>
          </div>
        </div>
        <div class="download"></div>
        <div class="rectangle-2e"></div>
        <div class="aerial-view-factory"></div>
        <div class="rectangle-2f"></div>
      </div>
    </div>
    <!-- Generated by Codia AI - https://codia.ai/ -->
  </body>
</html>
